# Default starter teams used by `team seed`.
# Format: "<slug>|<instructions>"
INITIAL_TEAMS=(
  "ux-flow-specialist|One teammate on user experience flows with agents focused on friction reduction, clarity, and intuitive interaction."
  "ui-design-system-expert|One teammate on UI design systems with agents focused on visual hierarchy, consistency, and conversion-oriented layouts."
  "product-manager|One teammate on product management with agents focused on MVP definition, prioritization, and user value alignment."
  "onboarding-optimizer|One teammate on onboarding optimization with agents focused on activation, retention, and time-to-value."
  "accessibility-analyst|One teammate on accessibility and usability with agents focused on inclusivity, standards, and edge-case scenarios."
  "backend-architect|One teammate on backend architecture with agents focused on scalability, APIs, and system design."
  "frontend-performance-engineer|One teammate on frontend performance with agents focused on rendering, responsiveness, and efficiency."
  "mobile-architecture-expert|One teammate on mobile architecture with agents focused on Flutter, iOS, Android, and best practices."
  "database-engineer|One teammate on database engineering with agents focused on schema design, indexing, and query performance."
  "devops-engineer|One teammate on DevOps with agents focused on CI/CD, infrastructure, and system reliability."
  "growth-strategist|One teammate on growth strategy with agents focused on acquisition channels, funnels, and experiments."
  "aso-seo-specialist|One teammate on ASO and SEO with agents focused on keywords, ranking, and organic visibility."
  "cro-specialist|One teammate on conversion rate optimization with agents focused on experiments and user behavior analysis."
  "viral-growth-analyst|One teammate on viral growth with agents focused on referral systems, loops, and network effects."
  "monetization-strategist|One teammate on monetization with agents focused on pricing, revenue models, and LTV optimization."
  "business-strategist|One teammate on business strategy with agents focused on market fit, positioning, and direction."
  "competitive-analyst|One teammate on competitive analysis with agents focused on benchmarking and differentiation."
  "unit-economics-expert|One teammate on unit economics with agents focused on revenue, cost structure, and profitability."
  "partnerships-lead|One teammate on partnerships with agents focused on distribution and strategic alliances."
  "devils-advocate|One teammate on critical thinking with agents focused on challenging assumptions and exposing flaws."
  "legal-compliance-advisor|One teammate on legal compliance with agents focused on privacy, regulations, and platform policies."
  "risk-analyst|One teammate on risk analysis with agents focused on failure scenarios and worst-case outcomes."
  "technical-debt-reviewer|One teammate on technical debt with agents focused on maintainability and long-term trade-offs."
  "security-engineer|One teammate on security with agents focused on vulnerabilities, abuse vectors, and system protection."
)
